### ISSUE TITLE
No option to define dockerfile custom name

### ISSUE THREAD

**Issue by shim52** [par-tec/docker-push-gar-image#1]
I can't specify a custom `Dockerfile` path, as the script refers to `/github/workspace/Dockerfile` by default.
Would be great if this can be edited.

**Comment by shim52** [comment]
I understand I need to use the `docker_context` field

**Comment by danielino** [comment]
docker_context: -f your_dockerfile

https://github.com/par-tec/docker-push-gar-image/blob/main/entrypoint.sh#L7

**Comment by shim52** [comment]
When specifying a Dockerfile under `docker_context` I get:
`unable to prepare context: context must be a directory`

**Comment by shim52** [comment]
@danielino 
From what I know the command should be: `docker build -f $INPUT_DOCKER_CONTEXT -t $IMAGE` so that we are able to inject a specific filename.
I tried pushing this into a new branch to create a PR that can be reviewed, but I don't have permission to push new branches.

**Comment by danielino** [comment]
docker_context: -f yourdockerfile ./

you don't know how to use docker. i suggest you to go for a crash course

**Comment by shim52** [comment]
@danielino 
I understood your response, but putting a specific docker build flag like: `-f` in the YAML is bad practice, as it's an implementation detail of docker build, but you call.
Good luck ✌️
